### ISSUE TITLE
Cannot position elements as fixed inside rolly-view

### ISSUE THREAD

**Issue by rnrh** [mickaelchanrion/rolly#15]
I am having trouble getting elements with `position: fixed;` to act as fixed elements inside of the rolly-view target. I would like rolly applied across the site, so the rolly-view target is the `<div>` directly inside of the `<body>` tag. 

I've tried positioning it fixed, but it scrolls as if it had default positioning. I've tried positioning absolutely as well, considering the rolly-view target itself is a fixed element, but had no luck with this either. I've simplified my markup as much as possible to avoid a possible issue happening between the rolly-view target and the element I am attempting to fix, which was previously many levels down, but was not able to resolve it.

Do you have a recommendation for solving this? I've pasted my simplified code below so you can better understand the structure of my DOM.

```javascript
import rolly from 'rolly.js';

const view = document.querySelector('.app');
const r = rolly({
  view,
  native: true,
  // other options
});
r.init();
```

```css
@import "../../node_modules/rolly.js/css/style.css";

.fixed-container {
    position: fixed;
    top: 0;
    left: 0;
    height: 500px;
    width: 500px;
}
```

```html
<html>
    <head>...</head>
    <body>
        <div class="app rolly-view">
            <div data-scene data-speed="1">
                <header>...</header>
                <div class="fixed-container">This is the element I am trying to fix</div>
                <div class="page-content">...</div>
            </div>
        </div>
    </body>
</html>
```
